version: '3.7'
services:

  back:
    restart: always
    container_name: "back"
    build:
      context: .
      dockerfile: Dockerfile
    command: python /usr/src/app/Shop/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env_back