version: '3.7'
services:

  oilback:
    restart: always
    container_name: "oilback"
    build:
      context: .
      dockerfile: Dockerfile
    command: python /usr/src/app/Shop/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env_back
  
  db:
    restart: on-failure
    container_name: "oildb"
    image: postgres:14.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=oil
      - POSTGRES_PASSWORD=GY6GKb7S
      - POSTGRES_DB=oil

volumes:
  postgres_data:
