# Generated by Django 4.1.5 on 2023-11-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentPressComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/equipment_press_composition_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentPressImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/equipment_press_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentSupplementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/equipment_supplement_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='OilImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/oil_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='OilMealImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/oil_meal_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=225)),
                ('answer', models.TextField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='OilMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('sub_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('volume', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('in_cooking', models.TextField(blank=True, max_length=5000, null=True)),
                ('in_cosmetology', models.TextField(blank=True, max_length=5000, null=True)),
                ('use_and_dosage', models.TextField(blank=True, max_length=5000, null=True)),
                ('composition', models.TextField(blank=True, max_length=5000, null=True)),
                ('keeping', models.TextField(blank=True, max_length=5000, null=True)),
                ('recipe', models.TextField(blank=True, max_length=5000, null=True)),
                ('oil_meal_catalog_image', models.ImageField(blank=True, null=True, upload_to='photos/oil_meal_photos/catalog/')),
                ('oil_meal_image', models.ManyToManyField(related_name='oil_meal_images', to='salagubmaslo.oilmealimage', verbose_name='Фото жмыха')),
            ],
        ),
        migrations.CreateModel(
            name='Oil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('sub_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('volume', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('in_cooking', models.TextField(blank=True, max_length=5000, null=True)),
                ('use_and_dosage', models.TextField(blank=True, max_length=5000, null=True)),
                ('composition', models.TextField(blank=True, max_length=5000, null=True)),
                ('keeping', models.TextField(blank=True, max_length=5000, null=True)),
                ('recipe', models.TextField(blank=True, max_length=5000, null=True)),
                ('oil_catalog_image', models.ImageField(blank=True, null=True, upload_to='photos/oil_photos/catalog/')),
                ('oil_image', models.ManyToManyField(related_name='oil_images', to='salagubmaslo.oilimage', verbose_name='Фото масла')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentSupplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('sub_title', models.TextField(blank=True, max_length=5000, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('equipment_supplement_catalog_image', models.ImageField(blank=True, null=True, upload_to='photos/equipment_supplement_photos/catalog/')),
                ('equipment_supplement_construct_image', models.ImageField(blank=True, null=True, upload_to='photos/equipment_supplement_photos/construct/')),
                ('equipment_supplement_construct', models.TextField(blank=True, max_length=5000, null=True)),
                ('equipment_supplement_image', models.ManyToManyField(related_name='equipment_supplement_images', to='salagubmaslo.equipmentsupplementimage', verbose_name='Фото дополнений')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentPress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('sub_title', models.TextField(blank=True, max_length=5000, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.IntegerField()),
                ('video_link', models.SlugField(blank=True, null=True)),
                ('equipment_press_catalog_image', models.ImageField(blank=True, null=True, upload_to='photos/equipment_press_photos/catalog/')),
                ('equipment_press_composition', models.ManyToManyField(related_name='equipment_press_composition_images', to='salagubmaslo.equipmentpresscomposition', verbose_name='Фото частей конструкции пресса')),
                ('equipment_press_image', models.ManyToManyField(related_name='equipment_press_images', to='salagubmaslo.equipmentpressimage', verbose_name='Фото пресса')),
            ],
        ),
    ]
