# Generated by Django 4.2.6 on 2023-10-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salagubmaslo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=250)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/oil_photos/')),
                ('volume', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.IntegerField()),
                ('description', models.CharField(max_length=2500)),
                ('in_cooking', models.CharField(max_length=1000)),
                ('in_cosmetology', models.CharField(max_length=1000)),
                ('use_and_dosage', models.CharField(max_length=1000)),
                ('composition', models.CharField(max_length=2500)),
            ],
        ),
    ]
