# Generated by Django 4.2.6 on 2023-10-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salagubmaslo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OilImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/oil_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='OilMealImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/oil_meal_photos/')),
            ],
        ),
        migrations.AlterField(
            model_name='qa',
            name='answer',
            field=models.TextField(max_length=100000),
        ),
        migrations.CreateModel(
            name='OilMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('sub_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('volume', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('in_cooking', models.TextField(blank=True, max_length=5000, null=True)),
                ('in_cosmetology', models.TextField(blank=True, max_length=5000, null=True)),
                ('use_and_dosage', models.TextField(blank=True, max_length=5000, null=True)),
                ('composition', models.TextField(blank=True, max_length=5000, null=True)),
                ('keeping', models.TextField(blank=True, max_length=5000, null=True)),
                ('recipe', models.TextField(blank=True, max_length=5000, null=True)),
                ('oil_meal_catalog_image', models.ImageField(blank=True, null=True, upload_to='photos/oil_meal_photos/catalog/')),
                ('oil_meal_image', models.ManyToManyField(related_name='oil_meal_images', to='salagubmaslo.oilmealimage', verbose_name='Фото жмыха')),
            ],
        ),
        migrations.CreateModel(
            name='Oil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('sub_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('volume', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('in_cooking', models.TextField(blank=True, max_length=5000, null=True)),
                ('use_and_dosage', models.TextField(blank=True, max_length=5000, null=True)),
                ('composition', models.TextField(blank=True, max_length=5000, null=True)),
                ('keeping', models.TextField(blank=True, max_length=5000, null=True)),
                ('recipe', models.TextField(blank=True, max_length=5000, null=True)),
                ('oil_catalog_image', models.ImageField(blank=True, null=True, upload_to='photos/oil_photos/catalog/')),
                ('oil_image', models.ManyToManyField(related_name='oil_images', to='salagubmaslo.oilimage', verbose_name='Фото масла')),
            ],
        ),
    ]
