# Generated by Django 4.2.6 on 2023-10-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salagubmaslo', '0002_oilimage_oilmealimage_alter_qa_answer_oilmeal_oil'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentPressComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/equipment_press_composition_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentPressImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/equipment_press_photos/')),
            ],
        ),
        migrations.AddField(
            model_name='oilimage',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='oilmealimage',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='EquipmentPress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('sub_title', models.TextField(blank=True, max_length=5000, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.IntegerField()),
                ('video_link', models.SlugField(blank=True, null=True)),
                ('equipment_press_catalog_image', models.ImageField(blank=True, null=True, upload_to='photos/equipment_press_photos/catalog/')),
                ('equipment_press_composition', models.ManyToManyField(related_name='equipment_press_composition_images', to='salagubmaslo.equipmentpresscomposition', verbose_name='Фото частей конструкции пресса')),
                ('equipment_press_image', models.ManyToManyField(related_name='equipment_press_images', to='salagubmaslo.equipmentpressimage', verbose_name='Фото пресса')),
            ],
        ),
    ]
