# Generated by Django 4.2.6 on 2023-10-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salagubmaslo', '0003_equipmentpresscomposition_equipmentpressimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentSupplementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/equipment_supplement_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentSupplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('sub_title', models.TextField(blank=True, max_length=5000, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.IntegerField()),
                ('equipment_supplement_catalog_image', models.ImageField(blank=True, null=True, upload_to='photos/equipment_supplement_photos/catalog/')),
                ('equipment_supplement_construct_image', models.ImageField(blank=True, null=True, upload_to='photos/equipment_supplement_photos/construct/')),
                ('equipment_supplement_construct', models.TextField(blank=True, max_length=5000, null=True)),
                ('equipment_supplement_image', models.ManyToManyField(related_name='equipment_supplement_images', to='salagubmaslo.equipmentsupplementimage', verbose_name='Фото дополнений')),
            ],
        ),
    ]
